# Generated by Django 4.1.3 on 2023-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0009_alter_add_room_room_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="add_room",
            name="Is_Available",
            field=models.BooleanField(default=True),
        ),
    ]
