# Generated by Django 4.1.3 on 2023-05-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0010_add_room_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add_room",
            name="Room_Number",
            field=models.CharField(max_length=255),
        ),
    ]
