# Generated by Django 4.1.3 on 2023-05-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0012_online_booking_room_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="online_booking",
            name="Room_Id",
        ),
    ]
