# Generated by Django 4.1.3 on 2023-05-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0014_online_booking_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_room",
            name="Room_Image",
        ),
    ]
