# Generated by Django 4.1.3 on 2023-05-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0015_remove_add_room_room_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="add_room",
            name="Room_Image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
