# Generated by Django 4.1.3 on 2023-06-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HotelApp", "0016_add_room_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="online_booking",
            name="Check_in",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="online_booking",
            name="Check_out",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
